mytrainingmodule:
  - title: "Stretching and Mobility"
    link: "/library/training/stretching/"
    tier: "Tier 1: Foundation & Maintenance"
    visibility: "Overt"
  - title: "Ground Mechanics"
    link: "/library/training/ground/"
    tier: "Tier 1: Foundation & Maintenance"
    visibility: "Overt"
  - title: "Daily Movement"
    link: "/library/training/daily/"
    tier: "Tier 1: Foundation & Maintenance"
    visibility: "Mask"
  - title: "Meditation and Empty Mind"
    link: "/library/training/meditation/"
    tier: "Tier 1: Foundation & Maintenance"
    visibility: "Covert"
  - title: "Ninja Sensory"
    link: "/library/training/ninja/"
    tier: "Tier 2: Instinct & Awareness"
    visibility: "Covert"
  - title: "Environment Awareness"
    link: "/library/training/environment/"
    tier: "Tier 2: Instinct & Awareness"
    visibility: "Covert"
  - title: "Fear Inoculation"
    link: "/library/training/fear/"
    tier: "Tier 2: Instinct & Awareness"
    visibility: "Mask"
  - title: "Somatic Awareness and Relaxation"
    link: "/library/training/somatic/"
    tier: "Tier 2: Instinct & Awareness"
    visibility: "Covert"
  - title: "Quarrel Movements"
    link: "/library/training/martialarts/quarrel"
    tier: "Tier 3: Combat Basics"
    visibility: "Overt"
  - title: "Basic Martial Arts"
    link: "/library/training/martialarts/basics"
    tier: "Tier 3: Combat Basics"
    visibility: "Overt"
  - title: "Common Tools Weaponry"
    link: "/library/training/martialarts/tools"
    tier: "Tier 3: Combat Basics"
    visibility: "Overt"
  - title: "Cultivation"
    link: "/library/training/cultivation/"
    tier: "Tier 6: Energy Cultivation"
    visibility: "Covert"