$("#jenesys20cover").click(function(){
    $(".grid-content").html(`
<h1>JENESYS (JAPAN EAST ASIA NETWORK OF EXCHANGE FOR STUDENTS AND YOUTHS) 2.0 REPORT</h1>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/055187a1-390f-487c-b9ea-6a10f49d9211-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Fajar Purnama in Tokyo</figcaption>
</figure>

<h3>Name: Fajar Purnama</h3>

<h3>Country: Indonesia</h3>

<h3>Occupation: Undergraduate Student</h3>

<h3>ID: 21DNM03030</h3>

<h3>Batch: 3</h3>

<h3>Group: J (Fukuoka)</h3>

<h2>DEPARTMENT OF ELECTRICAL ENGINEERING FACULTY OF ENGINEERING UDAYANA UNIVERSITY</h2>
	
`)
});

$("#jenesys20preface").click(function(){
    $(".grid-content").html(`

<h2>Preface</h2>

<p>I would like to express my gratitude to JICE (Japan International Cooperation Center), Consulate General of Japan, Udayana University and Prof. Dr. IGP Wirawan, MSc. for allowing me to participate in this program. I would like to thank my mother and father for supporting me in this program. I thank you to all that I cannot mention one by one for helping me in this program.</p><br />

<p>This will be report for the program JENESYS 2.0 that I participated. Overall it will be what I experienced and what I will contribute of this program. I would like to apologize if there are mistakes and missing things in this report.</p>

<p>Sincerely <br/> <br />                                                                                                                                                                                                                                                                               

Fajar Purnama	
`)
});

$("#jenesys20abstract").click(function(){
    $(".grid-content").html(`

<h2>Abstract</h2>

<p>JENESYS 2.0 is the second program of Japan East Asia Network of Exchange for Students and Youths where the participants are from 10 countries in ASEAN. The program that I followed was 3rd Batch. The participants are divided from Group A – L with each group consist of 30 participants with variety of 3 people from each 10 ASEAN countries. I belong to J group and have my program in Fukouka where other groups went to other places throughout Japan. The participants are also divided into 3 categories which are “Arts, Creative Works & Culture”, “Economics & Social Sciences”, and my category “Science & Technology”.</p> <br />

<p>This program was conducted by JICE (Japan International Coorperation Center). It is to prepare for the Integration in 2015 with the three pillars; ASEAN Politico-Security Community, ASEAN Economic Community, and ASEAN Socio-Cultural Community (JICE, 2013).</p> <br />

<p>I found in Japan that the city is well organized where business, residential, government, are centralized and seperated from each other. Everywhere in Japan I find the place free of rubbish. Their recycling management is great as well. In Oki Town the wastes are divided in 25 variety and 97% of the wastes are recycled. I also that the Japanese people I met are welcoming. There are different cultures in each area. I also found the people are very discipline and strict with time, in other words punctual. The services in every shop I've been are extraordinary. The clerks always smile, always greet every person that arrive and leave the shop. As expected Japan is high tech. The technology I saw in Toyota Motor Kyushu is very high. They're also working on green energy now days to reduce pollution generated by plants, and they're aiming for zero pollution.</p> <br />

<p>What I will do after this program is promoting Japan and ASEAN through ICT (Information Communication Technology). First I will promote websites of ASEAN and Japan here in Indonesia. Second I will establish links with my friends here in Indonesia to friends that I made from ASEAN and Japan on this program through free Medias and social Medias such as Yahoo Messenger, Facebook, Twitter, and final phase Skype or other video calling service. Third I will also upload this report to my blog <a href="https://0fajarpurnama0.github.io/bachelor">https://0fajarpurnama0.github.io/bachelor</a> as way of sharing my experience in Japan of this program.</p> <br />

<p>So through this I hope integration between ASEAN, and ASEAN to Japan can be established. The flow of investment will be accelerated. If this is relized our relation in daily lifes will be expanded, wisdom will be expanded. In the end I hope we can interract with ASEAN countries and Japan like interracting with our neighbours daily.</p>
	
`)
});

$("#jenesys20tableofcontents").click(function(){
    $(".grid-content").html(`

<h1>Table of Content</h1>
<ol>
<li>Cover</li>
<li>Preface</li>
<li>Table of Figures</li>
<li>Table of Tables</li>
<li>Abstract</li>
<li>Chapter 1 Introduction</li>
<li>Chapter 2 About JENESYS 2.0</li>
<li>Chapter 3 Findings in Japan
<ul>
<li>Environment and City Management</li>
<li>Culture and People</li>
<li>Technology</li>
</ul>
</li>
<li>Chapter 4 Contributions and Future Plans of This Program
<ul>
<li>Mission of This Program</li>
<li>Currently Possible Applications</li>
<li>Ideas Not Currently Applicable</li>
<li>Future Benefits of These Plans</li>
</ul>
<li>Chapter 5 Conclusion</li>
<li>Reference</li>
</ol>

`)
});

$("#jenesys20tableoffigures").click(function(){
    $(".grid-content").html(`

<h2>Table Of Figures</h2>

<ul>
<li>Figure 3.1 Image taken at Tokyo</li>
<li>Figure 3.2 Image taken somewhere at Fukuoka</li>
<li>Figure 3.3 Image taken somewhere at Fukuoka near Kururun</li>
<li>Figure 3.4 Image taken somewhere at Fukuoka where no rubbish was sighted</li>
<li>Figure 3.5 Waste division at Oki Town</li>
<li>Figure 3.6 Some recycled products at Oki Town</li>
<li>Figure 3.7 Some agricultural products in Fukuoka</li>
<li>Figure 3.8 People coming out of subway station and train arrived on time</li>
<li>Figure 3.9 Experiencing Noh Play at Ohari</li>
<li>Figure 3.10 Photo with Tanaguchi family</li>
<li>Figure 3.11 Automatic Toilet Seat</li>
<li>Figure 3.12 AR demo on pamphlet and condominium</li>
<li>Figure 3.13 Virtual fashion demonstration</li>
<li>Figure 3.14 Kinect on mechanical of car engine acceleration</li>
<li>Figure 3.15 Image taken on lecture by Fukuoka Prefectural Government</li>
<li>Figure 3.16 Image taken of presentation video on Toyota Motor Kyushu</li>
<li>Figure 3.17 Images taken at Laboratory of Spacecraft Environmental Interaction Engineering Kyutech</li>
<li>Figure 4.1 Daily contact with my JENESYS 2.0 group friends through Facebook</li>
<li>Figure 4.2 Putra Dananjaya (Indonesia) introduce himself to Daiki Takenaka (Japan)</li>
<li>Figure 4.3 Ridho Yurham (Indonesia) introduce himself to Daiki Takenaka (Japan)</li>
<li>Figure 4.4 Free medias I would use, Pidgin (multimessenger), Twitter, and Skype (video call service)</li>
<li>Figure 4.5 http://blog.unud.ac.id/fajarpurnama/jenesys-2-0-report-fajar-purnama-bali-indonesia-group-j-fukuoka</li>
</ul>
`)
});

$("#jenesys20tableoftables").click(function(){
    $(".grid-content").html(`

<h2>Table Of Tables</h2>

<ul>
<li>Table 4.1 List of websites to be promoted</li>
</ul>
`)
});

$("#jenesys20introduction").click(function(){
    $(".grid-content").html(`

<h2>Chapter 1 Introduction</h2>

<p>JENESYS stands for Japan East Asia Network of Exchange for Students and Youths. So the program JENESYS 2.0 batch 3 was held in Japan. The participants are University students from ASEAN countries with each countriy sent approximately 40 participants. The purpose of this program is to establish strong relationship between ASEAN countries, and ASEAN to Japan for the upcoming AEC (ASEAN Economic Community) 2015.</p> <br />

<p>There are 10 countries participating which were Brunei Darusalam, Cambodja, Indonesia, Laos, Malaysia, Myanmar, Philipin, Singapore, Thailand, and Vietnam. The participants were divided into 3 categories which are “Economics & Social Sciences”, “Arts, Creative Works & Culture”, and “Science & Technology”. All participants are divided into 12 groups with each group had 30 participants from 10 different countries, with 3 people from the same countries. Every group was dispersed throughout Japan. Group A & B went to Gifu, group C & D went to Mie, group E & F went to Kyoto, group G & H went to Nara, group I & J went to Fukuoka, group K went to Nagasaki, and group L went to Kumamoto. The program was from 23 June until 30 June, for a week.</p> <br />

<p>I belong in J group, in category of science and technology. With I group we went to Fukuoka. On the first day I arrive at Narita International Airport. I spent the rest of this day at Hotel Nikko Narita. There I was given orientation of the program and met my other group members. On the second day we're in Tokyo and heard a lecture by ASEAN-Japan Center. On the third day we went to Fukuoka by airplane. We went to Ohori Park and experience Noh Play. On the fourth day we heard a lecture by NEXT Systems, Co., Ltd and Fukuoka Prefectural Government. On the fifth day we heard a lecture at Oki Town Sustainable Centre “Kururun”, visited Toyota Motor Kyushu, heard a lecture about agricultural produce in Asakura, and have a home visit with local residents in Asakura City. On the sixth day we visited Kyushu Institute of Technology to have a lecture about the Institute, have a discussion we local undergraduate students, and had a workshop there for presentaion for the next day. The seventh day we returned to Tokyo and went to Gardem City Chiba to presentate our action plan after this program. Finally we returned to our own country the next day.</p> <br />

<p>The schedule for this group overall was mostly about knowing Japan and Fukuoka, and had an update of the latest technology. The most important thing on this program is the links that we have established among our friends from different countries and friends from Japan.</p>
	
`)
});

$("#jenesys20about").click(function(){
    $(".grid-content").html(`

<h2>Chapter 2 About JENESYS 2.0</h2>

<p>JENESYS stands for, Japan East Asia Region Network Exchange for Youths and Students, from this we can derive that this program will be held in Japan, the scale will be ASEAN and Japan, with purpose of network exchange, and targeted participants will be youths and students. The term 2.0 means it's the second program of JENESYS which means there was this program before.</p> <br />

<p>This program was conducted by JICE (Japan International Coorperation Center). JICE was established in March, 1977. Its main activities include: the management of international training courses for trainees from developing countries; youth exchange programs; assistance for students from overseas; and dispatching international cooperation personnel. In addition to 220 members of permanent and temporary staff, 1080 specialists of 31 languages belong to JICE, playing important roles in their respective fields such as technical trainings, international exchange, and Japanese language lessons (JICE, 2013).</p> <br />

<p>The objectives of this program are (JICE, 2013):</p>

<ol>
<li>To raise awareness of the university students of ASEAN member countries towards ASEAN Integration and ASEAN Economic Integration and to let the young generations of Japan to deepen the understanding of ASEAN countries and AEC (ASEAN Economic Community).</li>
<li>To learn about the activities of Japan and the key success factors for the economic revitalization in each area and to utilize the ideas for the economic development of each ASEAN member country.</li>
<li>To establish the AEC Youth Network to be given the function as a hub linking the young generation of the ASEAN member states and Japan for the future cooperation of the mutual benefit. For that purpose, the active dialogue of the mission members of the youth from the ASEAN countries and the youth of Japan is enhanced.</li>
<li>ASEAN (Association of Southeast Asia Nations) are setting for the Integration in 2015 with the three pillars; ASEAN Politico-Security Community, ASEAN Economic Community, and ASEAN Socio-Cultural Community.</li>
</ol>

`)
});

$("#jenesys20findingsinjapan").click(function(){
    $(".grid-content").html(`

<h2>Chapter 3 Findings In Japan</h2>

<h3>3.1 Environment and City Management</h3>

<p>I found the city's management well organized. I've seen the business district has its own block.</p>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/e22a2ea6-fa37-46ef-83ac-1d99c58310ee-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 3.1 Image taken at Tokyo</figcaption>
</figure>


<p>I've also seen the residential district and farms seperated.</p>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/a4bd1d53-082d-47b3-add6-fb1edfd053e2-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 3.2 Image taken somewhere at Fukuoka</figcaption>
</figure>


<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/c4504fd7-31b0-4ca6-bb4c-9be19ab22845-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 3.3 Image taken somewhere at Fukuoka near Kururun</figcaption>
</figure>


<p>Overall the towns are clean.</p>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/e0fa9fdd-1614-4703-9534-7e93aebcbb07-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 3.4 Image taken somewhere at Fukuoka where no rubbish was sighted</figcaption>
</figure>


<p>On 27th June 2013 from 09:30 – 11:00, we visited a recycling based town development Oki Town (Oki Town sustainable centre “Kururun”) and have a lecture of waste management there. Here the wastes are divided into 25 varieties.</p>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/7e02e958-e230-4956-9f69-3abef97e29ea-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 3.5 Waste division at Oki Town</figcaption>
</figure>


<p>Today at this town 97% of its waste are recycled which means there is only 3% rubbish and the rest can be use for something beneficial. For example fertilizer, electricity from biogas, diesel from kitchen waste. It's also thanks to local town's folk support to relize this. In the future they're aiming for zero waste town.</p>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/9aec35bd-6ad7-4737-b364-57ad0d165dd3-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 3.6 Some recycled products at Oki Town</figcaption>
</figure>


<p>I found that Fukuoka is also rich in agriculture. On 27th June 2013 from 16:00 – 17:00 we have lecture of agriculture at Asakura City. They're currently focusing on creating healthy and tasty snacks made from fruits and vegetables. Their reasons for this it's because youths today eats more snacks (like chips) and less fruit. So they like to create healthy chips made from fruits and vegetables.</p>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/daa55631-e700-4056-a782-d5808007d2df-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 3.7 Some agricultural products in Fukuoka</figcaption>
</figure>


<h3>3.2 Culture and People</h3>

<p>My first impression of the people when coming to Japan was they're strict with time. There's no tolerance of the word late in Japan. Everything is punctual. What I examine of how they can be punctual, it's because of subway train. Logically a subway train is clear channel transportation. Therefore the time of a subway train arrives is predictable and accurate.</p>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/393686ba-6d61-460a-9ac2-a473bf8c9189-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 3.8 People coming out of subway station and train arrived on time</figcaption>
</figure>


<p>Even though they advance their technology but they still preserve their culture. On 25th June 2013 from 14:30 – 16:30 we went to Ohari Park to experience Noh Play ourselves. This play was founded around 700 years ago on the age of the Samurai. I asked whether the audience needed to understand Japanese in order to enjoy this play. The answered, it's played in classical Japanese even native Japanese people find it hard to understand. Even though there is lack in understanding this play can still be enjoyed just witnessing the performance and costumes, similar to watching Operah.</p>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/7e1e70d4-823b-4018-b4d1-c5cdc1214992-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 3.9 Experiencing Noh Play at Ohari</figcaption>
</figure>


<p>From overall the Japanese people I have met, they're open, they really want to know of other peoples background and culture. The service that I witness there is very surprising. Every store I went to provides excellent customer service. The store clerks will always smile and says “irasshaimase” which is for welcoming someone whenever someone came. Most of the clerks have bright face when facing their clients. Other than that they also greet like “Ohaiyougozaimasu” which is Good morning. In the end they always thank their customer “arigatougozaimasu” which means thank you. Back to environment management, the people always keep their environment clean and tidy. They always throw their rubbish on the bin and arrange their surroundings well.</p> <br />

<p>On 27th June 2013 from 17:00 – 21:00 I have a home visit to Tanaguchi family. The entire family provides excellent hospitality even though we have trouble communicating because I could only speak Japanese a little. They're open people and likes to know how things are in my country.</p>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/c1ea6838-3200-4626-859f-c3703783b841-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 3.10 Photo with Tanaguchi family</figcaption>
</figure>


<h3>3.3 Technology</h3>

<p>My first impression of the technology in Japan was advance. My group J is a science and technology group. Most of our programs are explorations of technologies in Japan. There are two that had been mention above which are subway train and recycling factory in Oki Town. The everyday technology I experienced was automatic toilet seat.</p>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/8a7f847c-9dcf-4731-935a-318f9f3c4f53-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 3.11 Automatic Toilet Seat</figcaption>
</figure>



<p>The first program of technologies was on 26th June 2013 by NEXT Systems, Co., Ltd which was about stories behind its research and development, motion control system (Kinect in medical field, etc.) hands-on experience of Augmented Reality System, Kinect in fashion try-on, and Head Mount 3D Display. After that was demo of the technology. The first demo was AR of pamphlet and condominium. This technology works on android system by installing the application then connecting to the AR's network. Here I asked whether it needs its own connection or not. They answered they provided their on connection or it can be connected to the Internet. I also asked whether the current network capacity (most people called it bandwidth) is enough for today and future if all citizens are using this technology. They replied that technology is growing, today's current technology is enough but it's still growing, so it will be alright in the future. On my experience the android reads the 2D image then converts it to 3D or more detailed images. The second demo was virtual fashion demonstration where the person stands in front of the mirror and select virtual clothes to try on. The ideal technology is the same as trying clothes in changing room but virtually. So instead of wasting much energy on trying clothes in changing room, it's more energy efficient to use this virtual fashion mirror. This is also based on Kinect. The third demo was Kinect on mechanical of acceleration of cars. Kinect is an input device without any controller. Gestures lead to intuitive control. The picture is in 3D, the ideal technology is examining an object by touching except here is virtual.</p>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/a4f687b1-c29a-42a1-9dcb-b32c8b9239e2-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 3.12 AR demo on pamphlet and condominium</figcaption>
</figure>


<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/d06712bd-0461-462f-934d-3675fbea041e-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 3.13 Virtual fashion demonstration</figcaption>
</figure>


<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/3f3f354c-709a-4a2f-99f1-3e1a1237a5d3-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 3.14 Kinect on mechanical of car engine acceleration</figcaption>
</figure>


<p>The second program of technologies was lectures of hydrogen energy project, organic photonics and electronics R&D base, and ruby contents related policy measures also promoting of digital contents industry utilizing programming language ruby by Fukuoka Prefectural Government.</p>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/51ec6a83-ac8e-4a19-9d14-542f3e196967-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 3.15 Image taken on lecture by Fukuoka Prefectural Government</figcaption>
</figure>


<p>About the lecture of Hydrogen Energy is basically a fuel cell that generates electricity through the chemical reaction in which hydrogen and oxygen react to produce water and electricity. They said the energy produce is comparable to other electrical generator. The greatest advantage of this Hydrogen strategy is CO2 free. It doesn't produce CO2, so their future plan is CO2 free electrical power plants replacing those that generate high pollution. The next one was about organic EL display which EL stands for electroluminescence. Its main purpose is energy efficiency, since the material itself emits light so it saves the effort of emitting light, so it uses less energy. I asked on this session of how it compares to LCD. They have surprising answers which first of course it's much more efficient, second it's same cost to LCD, third it has same lifespan, and finally a shocking answer it has better performance than LCD (usually those with higher efficiency has lower performance). The next lecture it's about Ruby and digital industry content. Since time is limited they only introduce, and said they're recruiting undergraduates every year.</p> <br />

<p>The third program was about Oki Town Sustainable Centre “Kururun”, Recycling based town development which had already been explained in section 3.2.</p> <br />

<p>The fourth program was a company visit to Toyota Motor Kyushu.</p>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/4a9ea1b3-4aee-435e-b118-7fee5d36fe00-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 3.16 Image taken of presentation video on Toyota Motor Kyushu</figcaption>
</figure>


<p>To be honest it was too much for me to comprehend and we're forbid to take photos, but what I captured was they work with excellent system. We took tour on a real field of how cars are produced from zero until made. Their workers are humans and robots. What I saw, parts were carried by robots, and some simpler assembling was also done by robots. Other jobs and complicated assembling were done by humans. Their work was very systematic. Each phase of assembling are done by different people, with each phase has its time limit. If a worker encounters problems which cannot be solved within the time limit, the worker rings the bell and the flow will be stopped and others will come to help. After each phase of assembling there's an inspection and all data are recorded.</p> <br />

<p>The fourth program was about Agricultural produce in Asakura Technological development of Agri-Processing, already written on section 3.2.</p> <br />

<p>The last program regarding on technology was a visit to Kyutech (Kyushu Institute of Technology). We were divided into 2 groups 1 to go the Mechanical Engineering Laboratory. I chose to go to Laboratory of Spacecraft Environmental Interaction Engineering. I captured that on that laboratory they research on Spacecraft Environmental Interaction through artificial Space they created in tubes. In those tubes are artificial Space base on real Space. They conduct many kinds of experiments there.</p> <br />

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/cf7a7500-5ffa-4d08-851a-7c30371e840a-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 3.17 Images taken at Laboratory of Spacecraft Environmental Interaction Engineering Kyutech</figcaption>
</figure>

	
`)
});

$("#jenesys20contributionsandfutureplan").click(function(){
    $(".grid-content").html(`

<h1>Chapter 4 Contributions And Future Plans Of This Program</h1>

<h3> 4.1 Mission of This Program </h3>

<p>During the program there were few lectures that explained to us the mission of this program. First was program orientation on 23rd June 2013 from 14:00 – 17:00 at Hotel Nikko Narita. Second was lecture by ASEAN-Japan Center on 24th June 2013 from 10:00 – 11:30 at National Olympics Memorial Youth Center, Tokyo. Third was lecture by Fukuoka Prefectural Government of outline of Fukuoka Prefecture and exchange with ASEAN on 26th June 2013 from 14:00 – 17:00 at Fukuoka. Last one was workshop report presentation on 29th June 2013 from 16:00 – 17:00 at Symphonia E, 3F, TKP, Garden City Chiba (we did our workshop the day before). </p> <br />

<p>Overall the programs metioned above I derived that the mission of this program is to prepare for ASEAN integration in 3 pillars (stated in chapter 1) on 2015 and Japan wants to join in. With each group’s participants are from 10 different countries of ASEAN, we are to establish links between ASEAN countries with the first step befriend with participants in our group. The program also told us to establish links between ASEAN and Japan. We are to carry on ASEAN – Japan Centre’s will which is to promote export from ASEAN to Japan, to accelerate the flow of investment between ASEAN and Japan including the transfer of skills and technology, and to vitalize tourist traffic between ASEAN and Japan.</p>

<h3> 4.2 Currently Possible Applications</h3>

<p>I have befriended with all participants in my group, also with some others outside my group. Even up to today we’re still in contact almost daily through social media. </p>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/daf91e8f-e5d9-4c1b-bc86-5098d9156019-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 4.1 Daily contact with my JENESYS 2.0 group friends through Facebook</figcaption>
</figure>


<p>What I privately captured from this program is a mission to link my friends and everyone else in my home country to those links that I have established during this program.</p> <br />

<p>Since my backgrounds are in Electrical Engineering and ICT (Information Communication Technology) I would like to do this task using methods base on my backgrounds. I’d like to promote and I have already started of ASEAN and Japan through websites to first my friends. Since I just started I have promoted these websites below to around 10 of my friends at my home country. I planned to promote them to everyone I know. For Facebook I’ll ask my friends to like, for Twitter to follow, and for web pages I’ll ask to bookmark.</p>

<table border="1">
<caption>Tabel 4.1 List of websites to be promoted</caption>

<tr>
<th>NO</th>
<th>Website</th>
<th>Description</th>
</tr>
<tr>
<td>1</td>
<td>https://www.facebook.com/youthexchange.mofa</td>
<td></td>
</tr>

<tr>
<td>2</td>
<td>https://www.facebook.com/jenesys2jpasean</td>	
<td></td>
</tr>

<tr>
<td>3</td>
<td>https://www.facebook.com/ASEANCommunity	</td>
<td></td>
</tr>

<tr>
<td>4</td>
<td>https://www.facebook.com/aseanbeatEnglish</td>
<td></td>
</tr>

<tr>
<td>5</td>
<td>https://www.twitter.com/@asianbeat_chan_en</td>
<td></td>
</tr>

<tr>
<td>6</td>
<td>http://asianbeat.com</td>
<td></td>
</tr>

<tr>
<td>7</td>
<td>http://buyasean.jp</td>
<td></td>
</tr>

<tr>
<td>8</td>
<td>http://www.kyutech.ac.jp</td>	
<td></td>
</tr>


<tr>
<td>9</td>
<td>http://cent.ele.kyutech.ac.jp</td>
<td></td>
</tr>

<tr>
<td>10</td>
<td>http://cent.ele.kyutech.ac.jp/seic/seic_web.html</td>
<td></td>
</tr>

<tr>
<td>11</td>
<td>http://cent.ele.kyutech.ac.jp/index_e.php</td>
<td></td>
</tr>

<tr>
<td>12</td>
<td>http://laseine.ele.kyutech.ac.jp/english</td>
<td></td>
</tr>

<tr>
<td>13</td>
<td>http://www.toyota-kyushu.com</td>
<td></td>
</tr>

<tr>
<td>14</td>
<td>http://www.visitjapan.jp</td>
<td></td>
</tr>


<tr>
<td>15</td>
<td>http://www.jnto.go.jp</td>	
<td></td>
</tr>


<tr>
<td>16</td>
<td>http://www.fosa.jp</td>
<td></td>
</tr>

<tr>
<td>17</td>
<td>http://www.fissc.net</td>
<td></td>
</tr>

<tr>
<td>18</td>
<td>http://www.crossroadfukuoka.jp</td>
<td></td>
</tr>

<tr>
<td>19</td>
<td>http://www.pref.fukuoka.lg.jp</td>
<td></td>
</tr>

<tr>
<td>20</td>
<td>http://www.youtube.com/user/FukuokaPrefecture</td>
<td></td>
</tr>

<tr>
<td>21</td>
<td>http://www.mofa.go.jp</td>
<td></td>
</tr>

<tr>
<td>22</td>
<td>http://web-japan.org</td>
<td></td>
</tr>

<tr>
<td>23</td>
<td>http://www.vjc.jp</td>	
<td></td>
</tr>

<tr>
<td>24</td>
<td>http://www.denpasar.id.emb-japan.go.jp</td>
<td></td>
</tr>

<tr>
<td>25</td>
<td>http://www.kyushu-u.ac.jp/english/index.php	</td>
<td>Kyushu University </td>
</tr>

<tr>
<td>26</td>
<td>http://www.kyutech.ac.jp/english/index.html</td.
<td>Kyushu Institute of Technology</td>
</tr>

<tr>
<td>27</td>
<td>http://www.fwu.ac.jp/english</td>
<td>Fukuoka Women's University</td>
</tr>
	
<tr>
<td>28</td>
<td>http://www.kitakyu-u.ac.jp/another_language_site.html</td>
<td>The University of Kiyakyushu</td>
</tr>

<tr>
<td>29</td>
<td>http://www.seinan-gu.ac.jp/eng</td>
<td>Seinan Gakuin University</td>
</tr>

<tr>
<td>30</td>
<td>http://www.fukuoka-u.ac.jp/english</td>
<td>Fukuoka University</td>
</tr>

<tr>
<td>31</td>
<td>http://www.ip.kyusan-u.ac.jp/E/index.html</td>
<td>Kyushu Sangyo University</td>
</tr>

<tr>
<td>32</td>
<td>http://www.fit.ac.jp/EN/index.html</td>
<td>Fukuoka Institute of Technology</td>
</tr>

<tr>
<td>33</td>
<td>http://www.kurume-u.ac.jp/english/index.html</td>
<td>Kurume University</td>
</tr>

<tr>
<td>34</td>
<td>http://www.kindai.ac.jp/english</td>
<td>Kinki University Fukuoka Campus</td>
</tr>

<tr>
<td>35</td>
<td>http://www.fukujo.ac.jp/university</td>
<td>Fukuoka Jo Gakuin University</td>
</tr>
</table>

<p>As I stated above I have befriends with many people on this program from both ASEAN countries and Japan. It’d be better if I don’t keep it to myself so I’d like to introduce them to friends in Indonesia (ASEAN-Japanese friends to Indonesian friends). At least I should introduce but I’ll also ask them to introduce themselves and interract with the friends I met on this program (Indonesian friends to ASEAN-Japanese friends). I’d like to do this through ICT (Information Communication Technology). The beginning step is through social media such as Facebook and Twitter. I planned to show them the friends I made through this program. Then through posts I planned that they would introduce themeselves. The picture below shows that I never though my friends would be daring, it’s great though.</p>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/37219254-7527-4680-98d1-7cffe81d8ba3-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 4.2 Putra Dananjaya (Indonesia) introduce himself to Daiki Takenaka (Japan)</figcaption>
</figure>


<p>Next it would be nice that they could befriend at take the relationship to the next level throught chats. Finally, the last step I have in mind is they would interract daily through video conference, through Skype, facebook video call, yahoo messenger video call, etc. Today video call is the closest telecommunication to face-face conversation. That’s how far I could go as bridge between my friends in Indonesia and ASEAN-Japanese friends. I can only go as far as using free services because of economic limitation. Other than electricity, the hardware and software itself, and some paid internet services, accessing websites, social media, VOIP (Voice Over IP), and video calls are free.</p>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/85de1beb-c5e3-42da-8f04-a63d4e197d29-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 4.3 Ridho Yurham (Indonesia) introduce himself to Daiki Takenaka (Japan)</figcaption>
</figure>


<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/3b641117-a8e0-43b9-90ec-1ff397cd8d3c-original.png?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 4.4 Free medias I would use, Pidgin (multimessenger), Twitter, and Skype (video call service)</figcaption>
</figure>


<p>I will also share my experience by uploading my report on my blog <a href="https://0fajarpurnama0.github.io/bachelor">https://0fajarpurnama0.github.io/bachelor</a> http://blog.unud.ac.id/fajarpurnama (obselete) and other things such as photos, although all the photos I have uploaded on Facebook. I will volunteerly link or upload informations base on this program. Experiences such as the NOH play that I experienced, vist of NEXT Systems, Co., Ltd, lectures of Hydrogen Strategy, lectures of EL, lectures of Ruby and Digital Industry, visit of Recycling Center in Oki Town “Kururun”, visit of Toyota Motor Kyushu, lecture of agriculture in Asakura, home visit with Tanaguchi Family, visit of Kyutech, and the mission of this program from overall lectures and programs</p>

<figure>
  <img src="https://beta-static.photobucket.com/images/ii560/0fajarpurnama0/0/92742bb9-dae9-48f7-bb5d-1d25dd59a463-original.jpg?width=1920&height=1080&fit=bounds" alt="" width="100%">
  <figcaption>Figure 4.5 http://blog.unud.ac.id/fajarpurnama/jenesys-2-0-report-fajar-purnama-bali-indonesia-group-j-fukuoka</figcaption>
</figure>


<h3>4.3 Ideas Not Currently Applicable </h3>

<p>This section is ideas that today I cannot do which will remain for now as ideas. Still it’s some ideas that may prove beneficial but I alone for now could no accomplish due to limitation of economy and power.</p>

<p>My first idea is to establish a curriculum in education of establishing links between ASEAN countries and ASEAN to Japan. Why I stated this because just by providing facilities such as socialmedias and websites will not maximize the benefit of these facilities. There are lots of people who will not use these facilities unless these facilities are socialized, even more unless these people are told to. So I recommend that there will be a curriculum. There will be more socialization of establishing links between ASEAN countries and ASEAN to Japan, there will be lectures, and there will be task for students to access websites regarding to establishing links between ASEAN countries and ASEAN to Japan and making friends with people from outside home countries to socialmedias.</p>

<p>My second idea is to have more joint lectures between different regions and different countries via video conference, more seminars and more workshops through video conference. So I suggest there will be more video conferences between regions and countries.</p><br />

<p>My third idea is to promote more information regarding to ASEAN and Japan through local medias which are radio and television.</p><br />

<p>My fourth idea is to teach the young generations to be openminded. Openminded is the key for relationships between different people to succeed.</p> <br />

<p>My fifth idea is an R&D (Research and Development) on face to face technologies, whether it’s an affordable technology that makes long range telecommunication has the same quality as face to face communication or build a global affordable transportation so people can travel to other countries daily (people can afford to go to different countries everyday).</p>

<h3>4.4 Future Benefits of These Plans</h3>

<p>If these plans are relized then maximum acceleration of economic, exchange, and tourism flow can be achieved. Daily relationship will widen greatly, we not only interract with among our people but we will interract with other people from different background everyday. Real international school will be relized. For example like my primary school in Australia called Daceyville Public School. Back then my friends are not only natives Australian, but I have friends from Korea, China, Phillipin, Iran, India, and many others from all over the world. If each School has students from Indonesia, Japan, Philipin, Malaysia, Brunei Darusalam, Vietnam, Thailand, Laos, Myanmar, and Cambodja then there will be no more challenge of integration. In other words we succeeded. Growth on prosperity will be accelerated. It will be an even more fun world to live in. Other nations will follow us and sees us as an example.</p>
	
`)
});

$("#jenesys20conclusion").click(function(){
    $(".grid-content").html(`

<h2>Chapter 5 Conclusion</h2>

<p>I learned from this program that there will be integration of ASEAN and Japan in 2015. From this program we’re given a role to prepare for the integration. I already kept in touch with the friends I have made from ASEAN and Japan on this program through Facebook. I also have promoted the websites about ASEAN and Japan to some of my friends, and I have started to introduce my friends from ASEAN and Japan to my friends in Indonesia through Facebook. I will continue to establish links between my friends in Indonesia to my friends in ASEAN countries and Japan through Twitter, Pidgin Multimessenger for chatting, and finally Skype or through other video call services. Not to forget I will continue to promote and introduce this to more of my friends. I will share my experience through this report other than verbally. Once I finished writing this chapter I will upload it to my blog <a href="https://0fajarpurnama0.github.io/bachelor">https://0fajarpurnama0.github.io/bachelor</a>.</p> <br />

<p>My summary experience in Japan is that Japan is high tech country. The people are very welcoming, discipline especially in the field of punctuality. The services I found there everywhere is very warm hearted. They would greet anyone that comes in the shop and leaving the shop and they will always smile. The city management is very well organized where business district, residential area, and government are seperated and centralized. The city is clean which is no garbage found anywhere.</p> <br />

<p>Just one thing I find missed on this program is involving Japanese participants. There were participants from 10 different countries in ASEAN but there were no Japanese participants.</p> <br />
	
`)
});

$("#jenesys20reference").click(function(){
    $(".grid-content").html(`

<h2>Reference</h2>

<ul>
<li>JICE, 2013. Participants’ Handbook for ASEAN Economic Community (AEC) Youth Network. Japan International Coorperation Center : Japan</li>
<li>Download this report: <a href="http://www.mediafire.com/view/kwwa489xrjc3ano/JENESYS_2-0_REPORT.pdf">http://www.mediafire.com/view/kwwa489xrjc3ano/JENESYS_2-0_REPORT.pdf</a></li>
</ul>
	
`)
});